10.Best-Practices-and-Architecture-Lab/RealEstates/RealEstates.Web/Models/ErrorViewModel.cs
using System;

namespace RealEstates.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

10.Best-Practices-and-Architecture-Lab/RealEstates/RealEstates.Web/Controllers/DistrictsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RealEstates.Data;
using RealEstates.Models;

namespace RealEstates.Web.Controllers
{
    public class DistrictsController : Controller
    {
        private readonly RealEstateDbContext _context;

        public DistrictsController(RealEstateDbContext context)
        {
            _context = context;
        }

        // GET: Districts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Districts.ToListAsync());
        }

        // GET: Districts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var district = await _context.Districts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (district == null)
            {
                return NotFound();
            }

            return View(district);
        }

        // GET: Districts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Districts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] District district)
        {
            if (ModelState.IsValid)
            {
                _context.Add(district);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(district);
        }

        // GET: Districts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var district = await _context.Districts.FindAsync(id);
            if (district == null)
            {
                return NotFound();
            }
            return View(district);
        }

        // POST: Districts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] District district)
        {
            if (id != district.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(district);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DistrictExists(district.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(district);
        }

        // GET: Districts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var district = await _context.Districts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (district == null)
            {
                return NotFound();
            }

            return View(district);
        }

        // POST: Districts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var district = await _context.Districts.FindAsync(id);
            _context.Districts.Remove(district);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DistrictExists(int id)
        {
            return _context.Districts.Any(e => e.Id == id);
        }
    }
}

10.Best-Practices-and-Architecture-Lab/RealEstates/RealEstates.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RealEstates.Web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using RealEstates.Services;

namespace RealEstates.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IDistrictService districtService;

        public HomeController(IDistrictService districtService)
        {
            this.districtService=districtService;
        }

        public IActionResult Index()
        {
            var districts = this.districtService.GetTopDistrictsByAveragePPrice(1000);
            return View(districts);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

10.Best-Practices-and-Architecture-Lab/RealEstates/RealEstates.Web/Controllers/PropertiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RealEstates.Services;

namespace RealEstates.Web.Controllers
{
    public class PropertiesController:Controller
    {
        private readonly IPropertiesService propertiesService;

        public PropertiesController(IPropertiesService propertiesService)
        {
            this.propertiesService = propertiesService;
            this.propertiesService = propertiesService;
        }

        public IActionResult Search()
        {
            return this.View();
        }
        public IActionResult SearchByPriceRange()
        {
            return this.View();
        }

        public IActionResult DoSearchByDistrict()
        {
            
            return this.View();
          
        }

        //public IActionResult SearchByDistrict(string district)
        //{
        //    return this.View();
        //}
        //[Authorize(Roles = "Moderator")]
        public IActionResult DoSearch(int minPrice, int maxPrice)
        {
            //if (!this.User.IsInRole("Admin"))
            //{
            //    return this.BadRequest();
            //}
            var properties = this.propertiesService.SearchByPrice(minPrice, maxPrice);
            return this.View(properties);
        }
    }
}

10.Best-Practices-and-Architecture-Lab/RealEstates/RealEstates.Web/Views/Districts/Create.cshtml
@model RealEstates.Models.District

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>District</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

10.Best-Practices-and-Architecture-Lab/RealEstates/RealEstates.Web/Views/Districts/Delete.cshtml
@model RealEstates.Models.District

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>District</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

10.Best-Practices-and-Architecture-Lab/RealEstates/RealEstates.Web/Views/Districts/Details.cshtml
@model RealEstates.Models.District

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>District</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

10.Best-Practices-and-Architecture-Lab/RealEstates/RealEstates.Web/Views/Districts/Edit.cshtml
@model RealEstates.Models.District

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>District</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

10.Best-Practices-and-Architecture-Lab/RealEstates/RealEstates.Web/Views/Districts/Index.cshtml
@model IEnumerable<RealEstates.Models.District>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table table-striped table-sm table-small">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

10.Best-Practices-and-Architecture-Lab/RealEstates/RealEstates.Web/Views/Properties/DoSearch.cshtml
@using RealEstates.Services.Models;
@model IEnumerable<PropertyViewModel>
<h1>Search results</h1>
<table class="table table-sm table-striped table-bordered table-hover" align="center">
    <tr>
        <th>District</th>
        <th>Building Type</th>
        <th>Property Type</th>
        <th>Year</th>
        <th>Size</th>
        <th>Floor</th>
        <th>Price</th>
    </tr>
    @foreach (var property in this.Model)
    {
        <tr>
            <td>@property.District</td>
            <td>@property.BuildingType</td>
            <td>@property.PropertyType</td>
            <td>
                @property.Year
                @if (property.Year.HasValue)
                {
                    @:г.
                }
            </td>
            <td>@property.Size</td>
            <td>
                @if (property.Floor != "0/0")
                {
                    @property.Floor
                }
            </td>
            <td>@property.Price.ToString("0.00")€</td>
        </tr>
    }
</table>

10.Best-Practices-and-Architecture-Lab/RealEstates/RealEstates.Web/Views/Properties/DoSearchByDistrict.cshtml
@using RealEstates.Services.Models;
@model IEnumerable<PropertyViewModel>

<h1>Properties in this district</h1>
<table class="table table-sm table-striped table-bordered table-hover" align="center">
    <tr>
        <th>District</th>
        <th>Building Type</th>
        <th>Property Type</th>
        <th>Year</th>
        <th>Size</th>
        <th>Floor</th>
        <th>Price</th>
    </tr>
    @foreach (var property in this.Model)
    {
        <tr>
            <td>@property.District</td>
            <td>@property.BuildingType</td>
            <td>@property.PropertyType</td>
            <td>
                @property.Year
                @if (property.Year.HasValue)
                {
                    @:г.
                }
            </td>
            <td>@property.Size</td>
            <td>
                @if (property.Floor != "0/0")
                {
                    @property.Floor
                }
            </td>
            <td>@property.Price.ToString("0.00")€</td>
        </tr>
    }
</table>

10.Best-Practices-and-Architecture-Lab/RealEstates/RealEstates.Web/Views/Properties/Search.cshtml
@{
    ViewData["Title"] = "Search";
}

<h1>Search</h1>
@*<div class="btn-group">
    <button class="btn btn-primary">button 1</button>
    <button class="btn btn-secondary">button 2</button>
    <button class="btn btn-info">button 3</button>
</div>*@

<div class="dropdown">
    <button class="btn dropdown-toggle" data-toggle="dropdown">
        Search menu
    </button>
    <div class="dropdown-menu">
        <a class="nav-link text-dark" asp-area="" asp-controller="Properties" asp-action="SearchByPriceRange">Search by price</a>
        <a class="nav-link text-dark" asp-area="" asp-controller="Properties" asp-action="SearchByDistrictMaxProperties">Search by district</a>
    </div>
</div>

10.Best-Practices-and-Architecture-Lab/RealEstates/RealEstates.Web/Views/Properties/SearchByDistrictMaxProperties.cshtml
@using RealEstates.Services.Models;
@model IEnumerable<PropertyViewModel>

<h1>Search by district</h1>
<form method="get" action="/Properties/DoSearchByDistrict" class="col-md-6">
    <div class="dropdown">
        <button class="btn dropdown-toggle" data-toggle="dropdown">
            Search menu
        </button>
        <div class="dropdown-menu">
            @*<a href="#" class="dropdown-item">First district</a>*@
            @*@foreach (var property in this.Model)
            {
                <a href="#" class="dropdown-item">@property.District</a>
            }*@
            @*<a class="nav-link text-dark" asp-area="" asp-controller="Properties" asp-action="SearchByPriceRange">Search by price</a>
                <a class="nav-link text-dark" asp-area="" asp-controller="Properties" asp-action="SearchByDistrictMaxProperties">Search by district</a>*@
        </div>
    </div>
    <hr />
    <input type="submit" class="btn btn-primary float-right" value="Search" />
</form>

10.Best-Practices-and-Architecture-Lab/RealEstates/RealEstates.Web/Views/Properties/SearchByPriceRange.cshtml
@{
    ViewData["Title"] = "SearchByPriceRange";
}

<h1>Search properties by price</h1>
<form method="get" action="/Properties/DoSearch" class="col-md-6">
    <div>
        Min price: <input name="minPrice" class="form-control" />
    </div>
    <p />
    <div>
        Max price: <input name="maxPrice" class="form-control" />
    </div>
    <hr />
    <input type="submit" class="btn btn-primary float-right" value="Search" />
</form>